name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run specs
    strategy:
      matrix:
        ruby-version: ['2.7', '3.1']
        rails-version: ['rails-6', 'rails-6.1', 'rails-7', 'rails-7.2']
    env:
      BUNDLE_WITHOUT: release
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run rspec
        run: |
          bundle exec appraisal install
          cd spec/dummy
          bundle exec rails db:test:prepare
          cd ../..
          bundle exec appraisal ${{ matrix.rails-version }} rspec

  lint:
    runs-on: ubuntu-latest
    name: Run rubocop
    strategy:
      matrix:
        ruby-version: ['2.7']
    env:
      BUNDLE_WITHOUT: release
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run rubocop
        run: |
          bundle exec rubocop
