name: Publish
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
jobs:
  publish:
    name: Publish GitHub Package Registry
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install gems
        env:
          RAILS_VERSION: '6.1.7'
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
